import Gryffindor from './Img/gryffindor.png';
import Slytherin from './Img/slytherin.png';
import Ravenclaw from './Img/ravenclaw.png';
import Hufflepuff from './Img/hufflepuff.png';

import GryffindorBanner from './Img/gryf_banner.png';
import RavenclawBanner from './Img/raven_banner.png';
import HufflepuffBanner from './Img/huff_banner.png';
import SlytherinBanner from './Img/slyther_banner.png';


export const extraData = {

    Gryffindor: ["rgba(255, 0, 0, 0.678)", Gryffindor, GryffindorBanner],
    Ravenclaw: ["rgba(0, 0, 255, 0.678)", Ravenclaw, RavenclawBanner],
    Hufflepuff: ["rgba(255, 255, 0, 0.678)", Hufflepuff, HufflepuffBanner],
    Slytherin: ["rgba(172, 255, 47, 0.678)", Slytherin, SlytherinBanner]
}

export const history = {

    establishment: "Founded around the 9th century and 10th century by Godric Gryffindor, Rowena Ravenclaw, Helga Hufflepuff and Salazar Slytherin, Hogwarts was established in the Highlands of Scotland to educate young wizards and witches as well as to keep students safe from Muggle persecution. Theory has it that Rowena Ravenclaw came up with the name of Hogwarts after dreaming of a warty hog that led her to a cliff by a lake. Since then, Hogwarts educated most wizarding children with residence in Great Britain and Ireland, keeping its location hidden from other wizarding schools and Muggles.",
    middle: "About 300 years after the school was founded, the Triwizard Tournament was established as an interscholastic competition among the three most prestigious magical schools in Europe: Hogwarts, Beauxbatons, and Durmstrang. The tournament continued for six centuries before being discontinued. An attempt was made in the 1994–1995 school year to revive the tournament, but the consequential death of Cedric Diggory resulted in its permanent discontinuation.",
    admission: "According to the novels, admission to Hogwarts is selective, in that children who show magical ability will automatically gain a place, and squibs cannot attend the school as students (though they can work there in other roles, as Argus Filch does) A magical quill at Hogwarts detects the birth of magical children and writes their names into a large parchment book, but there is no admission test because 'you are either magical or you are not.' Every year, a teacher checks this book and sends a letter to the children who are turning eleven. Acceptance or refusal of a place at Hogwarts must be posted by 31 July. The letter also contains a list of supplies like spell books, uniform, and other things that the student will need. The prospective student is expected to buy all the necessary materials, normally from shops in Diagon Alley, a concealed street near Charing Cross Road in London that can be found behind the wizarding pub, The Leaky Cauldron. Students who cannot afford their supplies can receive financial aid from the school, as happened with the young orphan Tom Riddle.Letters to Muggle-born witches and wizards, who may not be aware of their powers and are unfamiliar with the concealed wizarding world, are delivered in person by a member of Hogwarts staff, who then explains to the parents or guardians about magical society, and reassures them regarding this news. Though the school is in Great Britain, its catchment area is the wider British Isles, as Irish students can also attend.Each student is allowed to bring an owl, a cat or a toad. Along with the acceptance letter, first-year students are sent a list of required equipment which includes a wand, subject books, a standard size 2 pewter cauldron, a set of brass scales, a set of glass or crystal phials, a kit of basic potion ingredients (for Potions), and a telescope (for Astronomy). The Hogwarts uniform consists of plain work robes in black, a plain black hat, a pair of protective gloves, and a black winter cloak with silver fastenings. Each uniform must contain the wearer's nametag. First years are not allowed a broomstick of their own, though an exception to this rule is made for Harry Potter in his first year after he demonstrates an excellent ability as a Seeker in Quidditch.",
    arrival: "The primary mode of transport to Hogwarts is the Hogwarts Express that students take at the start of each school year. Students board the train from the also fictional and hidden Platform 9¾ at King's Cross station in London. The train arrives at Hogsmeade station near Hogwarts, sometime after nightfall.From there, first-year students are accompanied by the 'Keeper of the Keys, Game and Grounds' (which was Hagrid during the first novel) to small boats, which magically sail across the lake and get them near the entrance of Hogwarts. The older students ride up to the castle in carriages pulled by creatures called Thestrals. When the first-year students initially arrive at the castle, they wait in a small chamber off the entrance hall until the older students have taken their seats, and then enter the Great Hall for the Sorting Ceremony to determine their House assignments. As Professor Minerva McGonagall said in Harry Potter and the Philosopher's Stone, 'The Sorting is a very important ceremony because, while you are here, your House will be something like your family within Hogwarts. You will have classes with the rest of your House, sleep in your House dormitory, and spend free time in your House common room.' After the Sorting Hat sings a song, each student in turn is seated upon the stool in front of the rest of the student body. The Hat is placed on the student's head, whereupon it examines his or her mind and assigns them to one of the four Houses based on abilities, personality, and preferences. After the Sorting Ceremony, the students and teachers enjoy a feast, prepared by the Hogwarts house-elves. If Dumbledore is feeling cheerful, he will lead the students in singing the school song.",
    houses: "Hogwarts is divided into four houses, each bearing the last name of its founder: Godric Gryffindor, Salazar Slytherin, Rowena Ravenclaw and Helga Hufflepuff. Throughout the school year, the houses compete for the House Cup, gaining and losing points based on actions such as performance in class and rule violations. The house with the highest end-of-year total wins and has its colours displayed in the Great Hall for the following school year. Each house also has its own Quidditch team that competes for the Quidditch Cup. These two competitions breed rivalries between the houses. Houses at Hogwarts are living and learning communities for their students. Each house is under the authority of one of the Hogwarts staff members. The Heads of the houses, as they are called, are in charge of giving their students important information, dealing with matters of severe punishment, and responding to emergencies in their houses, among other things. The dormitory and common room of a House are, barring rare exceptions, inaccessible to students belonging to other Houses; however, different houses will share classes as they are based on year group rather than House.In the early days of Hogwarts, the four founders hand-picked students for their Houses. When the founders worried how students would be selected after their deaths, Godric Gryffindor took his hat off and they each added knowledge to it, allowing the Sorting Hat to choose the students by judging each student's qualities and placing them in the most appropriate house. The student's own choices may affect the decision: the clearest example is the Hat telling Harry that he would do well in Slytherin in the first book, but ultimately selecting Gryffindor after Harry asks it not to put him in Slytherin.The translators of the books' foreign editions had difficulty translating the 'house' concept; in countries where this system does not exist, no word could adequately convey the importance of belonging to a house, the loyalty owed to it, and the pride taken in prizes won by the house.",
    subjects: "Being a school of magic, many subjects at Hogwarts differ from the studies of a typical school. Some subjects, such as History of Magic, derive from non-wizard – or muggle – subjects, but many others, such as charms and apparition classes, are unique to the wizarding world. There are twelve named teachers (referred to as Professors), each specialising in a single subject. All professors are overseen by a school head and deputy head. Transfiguration, Defence Against the Dark Arts, Charms, Potions, Astronomy, History of Magic, and Herbology are compulsory subjects for the first five years, as well as flying lessons. At the end of their second year, students are required to add at least two optional subjects to their syllabus for the start of the third year. The five choices are Arithmancy, Muggle Studies, Divination, Study of Ancient Runes and Care of Magical Creatures. According to J.K. Rowling, 'very specialised subjects such as alchemy are sometimes offered in the final two years, if there is sufficient demand. At the end of their fifth year, students take the Ordinary Wizarding Level (O.W.L.) examinations for all subjects in which they are enrolled. Each examination consists of a written knowledge test and, where applicable, a practical demonstration of skills before a panel of proctors from the Ministry of Magic. Students who achieve a high enough O.W.L. grade in a particular subject may take its advanced course for the final two years, in preparation for the Nastily Exhausting Wizarding Tests (N.E.W.T.) given at the end of the seventh year."
};